// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fapdrnwrkeivaxglyeiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcGRybndya2VpdmF4Z2x5ZWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTUxNjMsImV4cCI6MjA3NDM5MTE2M30.sUvSWJLtwfZ6FCQE359OCt1WVsRKPdL_DVzqSlk201Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});